import _Text from './Text';
import _Button from './Button';
import _Container from './Container';
import _Box from './Box';
import _TouchableBox from './TouchableBox';
import _TouchableBar from './TouchableBar';
import _DismissKeyboardView from './DismissKeyboardView';
//import _Spinner from './Spinner';
import _SettingsItem from './SettingsItem';
import _WithBadge from './WithBadge';

export const Container = _Container;
export const Box = _Box;
export const TouchableBox = _TouchableBox;
export const TouchableBar = _TouchableBar;
export const Text = _Text;
export const Button = _Button;
export const DismissKeyboardView = _DismissKeyboardView;
//export const Spinner = _Spinner;
export const SettingsItem = _SettingsItem;
export const WithBadge = _WithBadge;